# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 864c46bf68476b3667d29ea2c6b4ab5ec287e204d05ff11c89176fadd4926c5a62d02ce475ea1084532691c1300566bfd8cdf9c823dbee1f86752f5ff1e681f5

test:
  secret_key_base: 1b037fd704bea7b1d6c8041e40d0a8c4037c5d872a8dbe2f4bd80d1b2c7f50290adc2648b01a111b469d70562dfaf1e1013b511ecd838cb51eb2e10e4eb6819f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
